site_name: notebook
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
  palette: 
    primary: light blue
